---
driver:
  name: docker

provisioner:
  name: chef_zero
  client_rb:
    audit_mode: :enabled

platforms:
  - name: ubuntu-14.04
  - name: ubuntu-12.04
  - name: centos-6
  - name: windows-2012r2
    driver:
      name: ec2
      region: us-west-2
      availability_zone: b
      image_id: ami-f8f715cb
      instance_type: t2.small
      associate_public_ip: true
    transport:
      name: winrm

suites:
  - name: default
    run_list:
     - recipe[firefox_package_test]
    attributes:
